"""change_price_columns_to_integer

Revision ID: 2622474e79f5
Revises: b7322df1f6fd
Create Date: 2026-05-27 12:28:35.895140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2622474e79f5'
down_revision: Union[str, None] = 'b7322df1f6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NUMERIC → INTEGER 변환 시 PostgreSQL은 명시적 캐스팅이 필요합니다.
    # postgresql_using: 기존 소수점 값을 정수로 변환하는 SQL 표현식 (내림 처리)
    op.alter_column(
        'orders', 'price',
        existing_type=sa.NUMERIC(precision=20, scale=2),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='price::integer',  # 소수점 이하 버림으로 integer 변환
    )
    op.alter_column(
        'portfolio', 'avg_price',
        existing_type=sa.NUMERIC(precision=20, scale=2),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='avg_price::integer',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'avg_price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
