"""rename_security_to_item_master_add_survey_ai_tables

Revision ID: b7322df1f6fd
Revises: f9a55660762b
Create Date: 2026-05-27 11:34:35.966196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7322df1f6fd'
down_revision: Union[str, None] = 'f9a55660762b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. item_master 테이블 생성
    op.create_table('item_master',
    sa.Column('symbol_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('sector_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('symbol_code')
    )
    op.create_index(op.f('ix_item_master_symbol_code'), 'item_master', ['symbol_code'], unique=False)

    # 2. security를 참조하는 FK 먼저 제거
    op.drop_constraint('orders_symbol_code_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('portfolio_symbol_code_fkey', 'portfolio', type_='foreignkey')
    op.drop_constraint('price_history_symbol_code_fkey', 'price_history', type_='foreignkey')

    # 3. security 테이블 삭제
    op.drop_index('ix_security_symbol_code', table_name='security')
    op.drop_table('security')

    # 4. item_master를 참조하는 FK 새로 추가
    op.create_foreign_key(None, 'orders', 'item_master', ['symbol_code'], ['symbol_code'])
    op.create_foreign_key(None, 'portfolio', 'item_master', ['symbol_code'], ['symbol_code'])
    op.alter_column('price_history', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key(None, 'price_history', 'item_master', ['symbol_code'], ['symbol_code'])

    # 5. 신규 테이블 추가
    op.create_table('ai_propensity_advice',
    sa.Column('advice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_analysis_result', sa.Text(), nullable=True),
    sa.Column('ai_detailed_advice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('advice_id')
    )
    op.create_index(op.f('ix_ai_propensity_advice_advice_id'), 'ai_propensity_advice', ['advice_id'], unique=False)
    op.create_table('user_survey_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_user_survey_response_response_id'), 'user_survey_response', ['response_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key('price_history_symbol_code_fkey', 'price_history', 'security', ['symbol_code'], ['symbol_code'])
    op.alter_column('price_history', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.create_foreign_key('portfolio_symbol_code_fkey', 'portfolio', 'security', ['symbol_code'], ['symbol_code'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_symbol_code_fkey', 'orders', 'security', ['symbol_code'], ['symbol_code'])
    op.create_table('security',
    sa.Column('symbol_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('market_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sector_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol_code', name='security_pkey')
    )
    op.create_index('ix_security_symbol_code', 'security', ['symbol_code'], unique=False)
    op.drop_index(op.f('ix_user_survey_response_response_id'), table_name='user_survey_response')
    op.drop_table('user_survey_response')
    op.drop_index(op.f('ix_ai_propensity_advice_advice_id'), table_name='ai_propensity_advice')
    op.drop_table('ai_propensity_advice')
    op.drop_index(op.f('ix_item_master_symbol_code'), table_name='item_master')
    op.drop_table('item_master')
    # ### end Alembic commands ###
